package com.ntg.movieapiappcompose.ui.theme

import androidx.compose.ui.graphics.Color


val MdThemeLightPrimary = Color(0xFF006D3F)
val MdThemeLightOnPrimary = Color(0xFFFFFFFF)
val MdThemeLightPrimaryContainer = Color(0xFF84FAB2)
val MdThemeLightOnPrimaryContainer = Color(0xFF002110)
val MdThemeLightSecondary = Color(0xFF2B5EA7)
val MdThemeLightOnSecondary = Color(0xFFFFFFFF)
val MdThemeLightSecondaryContainer = Color(0xFFD7E3FF)
val MdThemeLightOnSecondaryContainer = Color(0xFF001B3F)
val MdThemeLightTertiary = Color(0xFFEDF4F4)
val MdThemeLightOnTertiary = Color(0xFFD3D3D3)
val MdThemeLightTertiaryContainer = Color(0xFFBEEAF7)
val MdThemeLightOnTertiaryContainer = Color(0xFF001F26)
val MdThemeLightError = Color(0xFFFF3D00)
val MdThemeLightErrorContainer = Color(0xFFFFDAD6)
val MdThemeLightOnError = Color(0xFFFFFFFF)
val MdThemeLightOnErrorContainer = Color(0xFF410002)
val MdThemeLightBackground = Color(0xFFF8FDFF)
val MdThemeLightOnBackground = Color(0xFF001F25)
val MdThemeLightSurface = Color(0xFFF8FDFF)
val MdThemeLightOnSurface = Color(0xFF001F25)
val MdThemeLightSurfaceVariant = Color(0xFFDCE5DB)
val MdThemeLightOnSurfaceVariant = Color(0xFFA6B7D8)
val MdThemeLightOutline = Color(0xFF717971)
val MdThemeLightInverseOnSurface = Color(0xFFD6F6FF)
val MdThemeLightInverseSurface = Color(0xFF00363F)
val MdThemeLightInversePrimary = Color(0xFF66DD98)
val MdThemeLightShadow = Color(0xFF000000)
val MdThemeLightSurfaceTint = Color(0xFF006D3F)
val MdThemeLightOutlineVariant = Color(0xFFC0C9C0)
val MdThemeLightScrim = Color(0xFF000000)
val MdThemeDarkPrimary = Color(0xFF66DD98)
val MdThemeDarkOnPrimary = Color(0xFF00391E)
val MdThemeDarkPrimaryContainer = Color(0xFF00522E)
val MdThemeDarkOnPrimaryContainer = Color(0xFF84FAB2)
val MdThemeDarkSecondary = Color(0xFF092040)
val MdThemeDarkOnSecondary = Color(0xFF002F65)
val MdThemeDarkSecondaryContainer = Color(0xFF1C3051)
val MdThemeDarkOnSecondaryContainer = Color(0xFFD7E3FF)
val MdThemeDarkTertiary = Color(0xFF242424)
val MdThemeDarkOnTertiary = Color(0xFF44464E)
val MdThemeDarkTertiaryContainer = Color(0xFF214C58)
val MdThemeDarkOnTertiaryContainer = Color(0xFFBEEAF7)
val MdThemeDarkError = Color(0xFFFFB4AB)
val MdThemeDarkErrorContainer = Color(0xFF93000A)
val MdThemeDarkOnError = Color(0xFF690005)
val MdThemeDarkOnErrorContainer = Color(0xFFFFDAD6)
val MdThemeDarkBackground = Color(0xFF131313)
val MdThemeDarkOnBackground = Color(0xFFDDDDDD)
val MdThemeDarkSurface = Color(0xFF131313)
val MdThemeDarkOnSurface = Color(0xFFFFFFFF)
val MdThemeDarkSurfaceVariant = Color(0xFF44464E)
val MdThemeDarkOnSurfaceVariant = Color(0xFF7E91B7)
val MdThemeDarkOutline = Color(0xFF8A938B)
val MdThemeDarkInverseOnSurface = Color(0xFF001F25)
val MdThemeDarkInverseSurface = Color(0xFFA6EEFF)
val MdThemeDarkInversePrimary = Color(0xFF006D3F)
val MdThemeDarkShadow = Color(0xFF000000)
val MdThemeDarkSurfaceTint = Color(0xFF66DD98)
val MdThemeDarkOutlineVariant = Color(0xFF414942)
val MdThemeDarkScrim = Color(0xFF000000)

